### ISSUE TITLE
NinePatch does not combine its transform with the RenderStates transform

### ISSUE THREAD

**Issue by salianifo** [Hapaxia/SelbaWard#10]
Line 247 of NinePatch.cpp should be: `	states.transform *= getTransform();` instead of `	states.transform = getTransform();`

**Comment by Hapaxia** [comment]
This is true and also true of multiple objects.

Feel free to create a pull request to fix this (for _all_ objects) before I do.

**Comment by Hapaxia** [comment]
List of objects that need this simple (single character addition) fix:
- Console Screen
- Console Screen (old)
- Gallery Sprite
- Nine Patch
- Pie Chart
- Progress Bar
- Ring
- Starfield
- Tile Map

> Elastic Sprite also needs to take this into account but it's more complex so will be solved separately.

**Comment by salianifo** [comment]
I had a quick glance at Elastic Sprite and since you apply the transform to the vertices manually, and don't modify the states.transform in the draw function, I don't think the same issue applies, but I haven't tested it.

**Comment by Hapaxia** [comment]
In Elastic Sprite, the transform passed into the draw function via render states is ignored and only the local transform is applied (as with the problem with the others before). I can see a solution to this and will be fixed soon.
