### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by JuliaRS** [Hapaxia/SelbaWard#12]
I try to use "Progress bar" example, some errors are appearing: 
error LNK2019: unauthorized external character reference "public: __cdecl selbaward::ProgressBar::ProgressBar(class sf::Vector2<float>)"
error LNK2019: ссылка на неразрешенный внешний символ "public: void __cdecl selbaward::ProgressBar::setRatio(float)"
error LNK2019: ссылка на неразрешенный внешний символ "public: void __cdecl selbaward::ProgressBar::setShowBackgroundAndFrame(bool)"

I absolutely don't understand why erros appeared, please help me

**Comment by eXpl0it3r** [comment]
Did you add the SelbaWard source files to your Visual Studio project?

**Comment by JuliaRS** [comment]
I included only <ProgressBar.hpp>.

**Comment by eXpl0it3r** [comment]
You need to add the SelbaWard source files to your Visual Studio project, so that the compiler knows the implementation.

**Comment by JuliaRS** [comment]
In project properties i added directory "src"

**Comment by JuliaRS** [comment]
selbaward::ProgressBar::ProgressBar(class sf::Vector2<float>)
selbaward::ProgressBar::setRatio(float) 
selbaward::ProgressBar::setShowBackgroundAndFrame(bool)
Only three methods of class ProgressBar is included in errors

**Comment by Hapaxia** [comment]
Are you compiling Selba Ward as a library and then including that or adding the files directly to your project?

**Comment by Hapaxia** [comment]
Closed due to no reply (over 2 months).
