### ISSUE TITLE
BitmapText does not check if internal font handle is null

### ISSUE THREAD

**Issue by JayhawkZombie** [Hapaxia/SelbaWard#13]
I'm using the most recent version of SelbaWard, and it appears that BitmapText, after settings the string property, in `updateVertices` will attempt to dereference its internal font pointer without checking for its null-ness.

The crash occurs when executing this statement:

`const int kerning{ (character < m_string.length() - 1) ? m_pBitmapFont->getKerning(m_string.substr(character, 2)) : 0 };` on line [139](https://github.com/Hapaxia/SelbaWard/blob/master/src/SelbaWard/BitmapText.cpp#L139), which will obviously go very poorly if one has not yet set the font.  

I think it would be reasonable to check for the texture for null, and the statement would look nearly identical:  

`const int kerning{ (character < m_string.length() - 1) && m_pBitmapFont ? m_pBitmapFont->getKerning(m_string.substr(character, 2)) : 0 };`

It would also allow us to set the properties in any order, much like SFML allows.

**Comment by Hapaxia** [comment]
It was always assumed that the font would be set before attemping to use it for anything. However, as with the SFML interface, it would be nicer to be able to set properties in any order.

This also means that setting the font should also update the vertices.

If the font is null, the vertices (and bounds) should not be updated at all (BitmapFont::getGlyph is just as problematic as BitmapFont::getKerning); they both should simply be cleared and that's it.
Also, if the font is null, the texture should not be set in the draw method. Of course, there's no reason to draw the vertices either.
