### ISSUE TITLE
Initialization Order.

### ISSUE THREAD

**Issue by degski** [Hapaxia/SelbaWard#20]
Not all fields are initialized in the correct order:

    1>..\src\SelbaWard\ConsoleScreen.cpp(685): warning : field 'm_buffers' will be initialized after field 'm_do' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreen.cpp(696): warning : field 'm_numberOfTilesPerRow' will be initialized after field 'm_palette' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreen.cpp(697): warning : field 'm_palette' will be initialized after field 'm_cursor' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreen.cpp(702): warning : field 'm_darkAttributeMultiplier' will be initialized after field 'm_characterMap' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreen.cpp(703): warning : field 'm_characterMap' will be initialized after field 'm_defaultPrintProperties' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreenOld.cpp(299): warning : field 'm_buffers' will be initialized after field 'm_do' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreenOld.cpp(308): warning : field 'm_numberOfTilesPerRow' will be initialized after field 'm_colors' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreenOld.cpp(310): warning : field 'm_palette' will be initialized after field 'm_cursor' [-Wreorder]
    1>..\src\SelbaWard\ConsoleScreenOld.cpp(312): warning : field 'm_attributes' will be initialized after field 'm_stretch' [-Wreorder]
    1>..\src\SelbaWard\Crosshair.cpp(99): warning : field 'm_vertices' will be initialized after field 'm_horizontalColor' [-Wreorder]
    1>..\src\SelbaWard\Crosshair.cpp(101): warning : field 'm_verticalColor' will be initialized after field 'm_window' [-Wreorder]
    1>..\src\SelbaWard\ElasticSprite.cpp(143): warning : field 'm_offsets' will be initialized after field 'm_weights' [-Wreorder]
    1>..\src\SelbaWard\ElasticSprite.cpp(146): warning : field 'm_usePerspectiveInterpolation' will be initialized after field 'm_requiresVerticesUpdate' [-Wreorder]
    1>..\src\SelbaWard\ElasticSprite.cpp(148): warning : field 'm_textureRect' will be initialized after field 'm_pTexture' [-Wreorder]
    1>..\src\SelbaWard\GallerySprite.cpp(51): warning : field 'm_vertices' will be initialized after field 'm_pTexture' [-Wreorder]
    1>..\src\SelbaWard\GallerySprite.cpp(53): warning : field 'm_exhibits' will be initialized after field 'm_currentExhibit' [-Wreorder]
    1>..\src\SelbaWard\NinePatch.cpp(150): warning : field 'm_textureRectangle' will be initialized after field 'm_trimmedSize' [-Wreorder]
    1>..\src\SelbaWard\ProgressBar.cpp(40): warning : field 'm_size' will be initialized after field 'm_showBar' [-Wreorder]
    1>..\src\SelbaWard\ProgressBar.cpp(47): warning : field 'm_textureRectangle' will be initialized after field 'm_backgroundTexture' [-Wreorder]
    1>..\src\SelbaWard\SpinningCard.cpp(42): warning : field 'm_depth' will be initialized after field 'm_vertices' [-Wreorder]
    1>..\src\SelbaWard\Spline.cpp(131): warning : field 'm_showHandles' will be initialized after field 'm_useBezier' [-Wreorder]
    1>..\src\SelbaWard\Sprite3d.cpp(93): warning : field 'm_backTextureOffset' will be initialized after field 'm_size' [-Wreorder]
    1>..\src\SelbaWard\Sprite3d.cpp(104): warning : field 'm_isBackFacing' will be initialized after field 'm_compactTransformMatrix' [-Wreorder]

No biggie, but could be better.

**Comment by Hapaxia** [comment]
Why is **m_buffers** being initialised after **m_do** a problem?

**Comment by Hapaxia** [comment]
Why is **m_buffers** being initialised after **m_do** considered erroneous (or is it before that is wrong)?

**Comment by eXpl0it3r** [comment]
The order of the member variables initialization should be the same as the order they were declared.

**Comment by Hapaxia** [comment]
Oh my! This means that I haven't listed them in the same order in the initialisation list as the order that they are declared?

**Comment by eXpl0it3r** [comment]
Yes, that's what `-Wreorder` warns about. 🙂

**Comment by Hapaxia** [comment]
Thank you!
I'll make more of an effort with newer things and will see to fixing the current ones when I can unless someone else want to fix them...

**Comment by degski** [comment]
Sorry for missing posts on this issue. Yes, it's like eXpl0it3r states, a basic rule in C++, it's violated. Whether that leads to problems depends on the code and the implementation of your compiler and/or STL library. The fact that "it works" is no good. The fixes are easy, the files and line-numbers are listed in my original post. If it's not easy [which is possible if there are dependent initializations, I didn't look at the detail], that means there is a real issue, that needs to be properly addressed, usually by moving some stuff to the body of the constructor, or in the worst case have a 2-stage constructor/init-function.

**Comment by Hapaxia** [comment]
I think it's overstating its seriousness by describing it as violating a rule of C++.
It seems that C++ simply states that they should be constructed in the order declared regardless of their order listed in the initialisation. This means that listing them in the same order is not required; they should be constructed correctly anyway.
So, it's more a matter of style or standard than anything else but I am not saying that I don't agree with it and will make efforts to follow this standard.

I made no comment that suggested that I would not 'fix' this so I am unsure why you felt the need to convince me further.
Also, there should not be any problems with fixing it since they were always getting constructed in that order anyway :)

**Comment by eXpl0it3r** [comment]
Just FYI the standard doesn't require you to write it that way, but the warning is completely justified, because it may lead to wrong assumptions of what is already initialized and what isn't. 😉

**Comment by Hapaxia** [comment]
I agree that it's a good style to aim for and the warnings are useful for that; they are only guides in this case.

I should clarify that when I used the word standard, I meant standard practices/styles rather than the official C++ standard.

Thanks for the advice. Learn something new every day :smile:

**Comment by degski** [comment]
@Hapaxia Alrite, I overdid it. Learn something new every day 😄
