### ISSUE TITLE
(ElasticSprite) Texture cut off when perspective interpolation enabled

### ISSUE THREAD

**Issue by hadrosoft** [Hapaxia/SelbaWard#22]
When an ElasticSprite has perspective mode enabled, the texture seems to be offset by some amount, cutting off the right and bottom sides of the image, and even pulling in pixels from beyond the left and top edges. The problem does not occur in bilinear mode.

**Bilinear:**
![bilinear_1](https://user-images.githubusercontent.com/48849197/54868770-75363300-4d66-11e9-8d7d-70df87abeaef.png)

![bilinear_2](https://user-images.githubusercontent.com/48849197/54868771-79fae700-4d66-11e9-8f6e-c8202f2dc998.png)

**Perspective:**
![perspective_1](https://user-images.githubusercontent.com/48849197/54868774-7cf5d780-4d66-11e9-9758-3b510b22d602.png)

![perspective_2](https://user-images.githubusercontent.com/48849197/54868776-82532200-4d66-11e9-9cf2-4f1c48010999.png)

Furthermore, the degree to which the sprite gets cut off varies depending on the textureRect's position: the farther it is from the texture's top-left corner, the more severe. At offset {0, 0}, there's no cutoff at all. I've included some testing code, and three different images that demonstrate this. _(Uncomment the appropriate init code to test each image.)_

```
    static bool              init     = false;
    static sw::ElasticSprite sprite;
    static bool              bilinear = true;
    static sf::Texture       tex;

    if (!init) {
//        //  No padding
//        tex.loadFromFile("/home/hadrosoft/Desktop/test_image.png");
//        tex.setSmooth(true);
//        sprite.setTexture(tex, true);

//        //  Small padding
//        tex.loadFromFile("/home/hadrosoft/Desktop/test_image_padded_small.png");
//        tex.setSmooth(true);
//        sprite.setTexture(tex);
//        sprite.setTextureRect({220, 177, 508, 508});

        //  Big padding
        tex.loadFromFile("/home/hadrosoft/Desktop/test_image_padded_large.png");
        tex.setSmooth(true);
        sprite.setTexture(tex);
        sprite.setTextureRect({2664, 1956, 508, 508});


        sprite.setPosition({100, 100});
        sprite.setUseShader(true);
        if (bilinear) {
            sprite.activateBilinearInterpolation();
        }
        else {
            sprite.activatePerspectiveInterpolation();
        }
        init = true;
    }

    static sf::Vector2f vtx[4] = {{0, 0}, {0, 0}, {0, 0}, {0, 0}};
    static int          vi     = 0;
    static const float  inc    = 2.0f;

    /*  The following keyboard input stuff is just pseudocode for simplicity;
        sub in your favorite keyboard handler, or just modify the vertex offsets
        in vtx[] manually.
        This isn't even strictly necessary, since the bug shows no matter what
        the vertex offsets are.     */

    if (input.key_new_press(" ")) {
        ++vi;
        if (vi == 4) { vi = 0; }
        std::cout << "Now modifying vertex #" << vi << std::endl;
    }
    if (input.key_is_pressed("Up")) {
        vtx[vi].y -= inc;
    }
    else if (input.key_is_pressed("Down")) {
        vtx[vi].y += inc;
    }
    if (input.key_is_pressed("Left")) {
        vtx[vi].x -= inc;
    }
    else if (input.key_is_pressed("Right")) {
        vtx[vi].x += inc;
    }
    if (input.key_new_press("P")) {
        bilinear = !bilinear;
        if (bilinear) {
            sprite.activateBilinearInterpolation();
        }
        else {
            sprite.activatePerspectiveInterpolation();
        }
        std::cout << "Interpolation: " << ((bilinear) ? "Bilinear" : "Perspective") << std::endl;;
    }

    for (int x = 0; x < 4; ++x) {
        sprite.setVertexOffset(x, {vtx[x].x, vtx[x].y});
    }

    window.clear(sf::Color(192, 192, 192, 255));
    window.draw(sprite);
```

**SFML version:** 2.4.2
**Testing environment:** Ubuntu 18.04.2
**GPU:** GeForce GTX 950

**Test images: _(Right click -> Save As...)_**
[test_image.png](https://user-images.githubusercontent.com/48849197/54868890-d3afe100-4d67-11e9-948b-9ff36d65c567.png)
[test_image_padded_small.png](https://user-images.githubusercontent.com/48849197/54868894-d9a5c200-4d67-11e9-90ea-26688872533a.png)
[test_image_padded_large.png](https://user-images.githubusercontent.com/48849197/54868891-d579a480-4d67-11e9-8e32-a82a5900e42d.png)

**Comment by Hapaxia** [comment]
After creating a test application from your test code, I see the problem with the large padding image.
It's possible that this may be due to accuracy at high values (similar to a floating point accuracy). The perspective interpolation requires a 'weight' value for each vertex that needs to be interpolated with the vertex. Unfortunately, SFML vertices do not provide a spare float for this so the integer values of colour were used to the floating point value as they are automatically interpolated with the vertex. Obviously, though, this isn't perfect; it can result in slightly 'off' values. With larger values, these off values become proportional and are more visible.
You can see how it sort of jumps back and forth every few positions when moving a vertex. That's (I think) the accuracy of the weight being not high enough.

As a possible fix, however, I'll look into approaching it in a similar way to the bi-linear interpolation and supply many uniforms and make the shader calculate everything inside. If I can.

**Comment by Hapaxia** [comment]
I've updated Elastic Sprite to v1.2, which mostly concentrates on fixing this problem although it now allows colours to be used with perspective interpolation!

Please test out this latest version and let me know if it fixes the problem for you.
If you find that this problem still occurs, I can re-open and investigate.

**Comment by hadrosoft** [comment]
Wow, that was fast -- thanks! I'll test it out immediately.

Awesome to hear about the colors, too -- I had some hacky code in my game to work around that limitation, and it'll be fun to be able to rip that code out ^_^

**Comment by hadrosoft** [comment]
Tested -- it works!

**Comment by Hapaxia** [comment]
Excellent! That's good to hear!

One thing you may want to note is that the colour interpolation during perspective interpolation is reverted to the usual method; that is, each triangle is interpolated separately, just for the colours.
