### ISSUE TITLE
Error LNK2019 

### ISSUE THREAD

**Issue by nick-redwill** [Hapaxia/SelbaWard#28]
I'm trying to include a Line.hpp file, but when linking a program I get an error "unresolved external symbol". Am I doing something wrong or do I need to include some lib file?

**Comment by Hapaxia** [comment]
All drawables require their .cpp counterpart.  
The two main options are:  
1. build Selba Ward as a (static) library and link to it as you would other libraries,
2. copy the files required for only the drawables you want to directly into your project and compile with it.

Remember, each drawable requires its .hpp and .cpp and also Common.hpp.
Some drawables require (or can be extended by using) other files (e.g. Bitmap Text requires Bitmap Font as well).

**Comment by nick-redwill** [comment]
Oh, thank you! I included "Line.cpp" and it works!
