### ISSUE TITLE
Ring shape - incorrect size

### ISSUE THREAD

**Issue by larinius** [Hapaxia/SelbaWard#31]
Ring shape 10 times bigger than SFML circle.  When I put ring radius 64 it cowers half of my screen.
Same time when use SFML circle with radius 32, I got exactly what expected - circle with proper size.

**Comment by Hapaxia** [comment]
This is certainly not the intended behaviour but I am unable to create this error.
Can you provide a very simple complete code that causes this?

**Comment by Hapaxia** [comment]
Does the [Simple Example](https://github.com/Hapaxia/SelbaWard/wiki/Ring#simple-example) work as expected in the [Wiki for Ring](https://github.com/Hapaxia/SelbaWard/wiki/Ring)?

**Comment by Hapaxia** [comment]
Closed due to no reply.

**Comment by Hapaxia** [comment]
Closed due to no reply.
